import Link from "next/link";

export default function Home() {
  return (
    <main style={{ maxWidth: 720, margin: "80px auto", padding: "0 24px", fontFamily: "system-ui, sans-serif" }}>
      <h1 style={{ fontSize: 32, marginBottom: 12 }}>Your generated app</h1>
      <p style={{ color: "#555", lineHeight: 1.6 }}>
        This project was generated by prompt-to-app. Explore the full AI blueprint
        — every agent&apos;s output — on the docs page.
      </p>
      <Link
        href="/docs"
        style={{
          display: "inline-block",
          marginTop: 24,
          padding: "10px 18px",
          borderRadius: 10,
          background: "#6d8bff",
          color: "#fff",
          textDecoration: "none",
          fontWeight: 600,
        }}
      >
        View AI Blueprint →
      </Link>
    </main>
  );
}
